apiVersion: v1
kind: Service
metadata:
  name: brm-backend
  labels:
    app.kubernetes.io/name: brm-backend
spec:
  selector:
    app.kubernetes.io/name: brm-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000