apiVersion: v1
kind: Service
metadata:
  name: brms-api
  labels:
    app.kubernetes.io/name: brms-api
spec:
  selector:
    app.kubernetes.io/name: brms-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000