name: CSV Rule Tests

on:
  push:
    branches:
      - main
      - dev
      - feature/multitenant-improvements #TODO: Remove before merge
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows us to trigger this workflow from elsewhere (like the rules repo)

jobs:
  csv-rule-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      # Checks for names of rule repositories in RULES_REPOSITORIES environment variable
      # Clones the repositories into their own folders and runs the tests for them
      - name: Clone additional repositories and run tests
        run: |
          IFS=',' read -r -a repos <<< "${{ vars.RULES_REPOSITORIES }}"
          for repo in "${repos[@]}"; do
            git clone -b dev "https://github.com/$repo.git" "$repo"
            npm run test:rules $repo
          done
