
name: CSV Rule Tests

on:
  push:
    branches:
      - main
      - feature/pipeline-rule-tests
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows us to trigger this workflow from elsewhere (like the rules repo)

jobs:
  csv-rule-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Clone additional repository
        run: git clone -b feature/pipeline-rule-tests https://github.com/bcgov/brms-rules.git brms-rules

      - name: Run CSV tests
        run: npm run test:rules