name: Docker Image CI

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: user/app:latest

    - name: Install CLI tools from OpenShift Mirror
      uses: redhat-actions/openshift-tools-installer@v1
      with:
  
        # "mirror" is the default source, so this is optional.
        source: "mirror"
  
        # Installs the latest kam release.
        kam: "latest"
  
        # Installs the latest release of oc with the major version 3.
        # This is equivalent to "3.x" or "^3".
        oc: "3"
  
        # Installs the latest release of odo with the major version 2, and the minor version 0.
        # This would install odo 2.0.3, but not odo 2.1.0.
        odo: "2.0"
  
        # This exact version will install version 0.11.0 of Tekton, no other version.
        tkn: "0.11.0"

    - name: Authenticate and set context
      uses: redhat-actions/oc-login@v1
      env:
        # These can be stored in secrets, if desired.
        OPENSHIFT_NAMESPACE: eb0f74-test
  
      with:
        # URL to your OpenShift cluster.
        # Refer to Step 2.
        openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
  
        # Authentication Token. Can use username and password instead.
        # Refer to Step 3.
        openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
  
        # Disables SSL cert checking. Use this if you don't have the certificate authority data.
        insecure_skip_tls_verify: true
  
        # Optional - this sets your Kubernetes context's current namespace after logging in.
        namespace: ${{ env.OPENSHIFT_NAMESPACE }}
